CREATE TABLE FILM (
    ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    CIM VARCHAR(25) NOT NULL,
    RENDEZO VARCHAR(25) NOT NULL,
    SZINESZ VARCHAR(25) NOT NULL,
    LEIRAS VARCHAR(100) NOT NULL,
    HOSSZ INT NOT NULL,
    KORHATAR INT NOT NULL
);

CREATE TABLE VETITES (
    ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    FILM_ID INT CONSTRAINT FK_VETITES_FILM_TEREM REFERENCES FILM ON DELETE CASCADE ON UPDATE RESTRICT,
    TEREM_ID INT CONSTRAINT FK_VETITES_TEREM_FILM REFERENCES TEREM ON DELETE CASCADE ON UPDATE RESTRICT,
    MIKOR TIMESTAMP
);

CREATE TABLE TEREM (
    ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    NEV VARCHAR(25) NOT NULL,
    FEROHELY INT NOT NULL
);

CREATE TABLE SZEKTEREM (
    ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    TEREM_ID INT CONSTRAINT FK_SZEKTEREM_TEREM_SZEK REFERENCES TEREM ON DELETE CASCADE ON UPDATE RESTRICT,
    SZEK_ID INT CONSTRAINT FK_SZEKTEREM_SZEK_TEREM REFERENCES SZEK ON DELETE CASCADE ON UPDATE RESTRICT
    
);

CREATE TABLE SZEK (
    ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    SOR INT NOT NULL,
    OSZLOP INT NOT NULL
);

CREATE TABLE FOGLALAS (
    ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    SZEK_ID INT CONSTRAINT FK_FOGLALAS_SZEK_FELHASZNALO REFERENCES SZEK ON DELETE CASCADE ON UPDATE RESTRICT,
    FELHASZNALO_ID INT CONSTRAINT FK_FOGLALAS_FELHASZNALO_SZEK REFERENCES FELHASZNALO ON DELETE CASCADE ON UPDATE RESTRICT
);

CREATE TABLE FELHASZNALO (
    ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    NEV VARCHAR(25) NOT NULL,
    JOG INT NOT NULL
);

CREATE TABLE MOZI (
    ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    NEV VARCHAR(30) NOT NULL
);

CREATE TABLE TARTALMAZ (
    ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    MOZI_ID INT CONSTRAINT FK_TARTALMAZ_MOZI_TEREM REFERENCES MOZI ON DELETE CASCADE ON UPDATE RESTRICT,
    TEREM_ID INT CONSTRAINT FK_TARTALMAZ_TEREM_MOZI REFERENCES TEREM ON DELETE CASCADE ON UPDATE RESTRICT
);