CREATE TABLE FELHASZNALO (
    ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    NEV VARCHAR(10) NOT NULL,
    JOG INT NOT NULL
);

CREATE TABLE FILM (
    ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    CIM VARCHAR(20) NOT NULL,
    RENDEZO VARCHAR(20),
    SZINESZ VARCHAR(20),
    LEIRAS VARCHAR(20),
    HOSSZ INT NOT NULL,
    KORHATAR INT NOT NULL
);

CREATE TABLE MOZI (
    ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    NEV VARCHAR(20) NOT NULL
);

CREATE TABLE TEREM (
    ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    NEV VARCHAR(20) NOT NULL,
    FEROHELY INT NOT NULL
);

CREATE TABLE TARTALMAZ (
    ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    MOZI_ID INT CONSTRAINT FK_TARTALMAZ_MOZI_TEREM REFERENCES MOZI ON DELETE CASCADE ON UPDATE RESTRICT,
    TEREM_ID INT CONSTRAINT FK_TARTALMAZ_TEREM_MOZI REFERENCES TEREM ON DELETE CASCADE ON UPDATE RESTRICT
);

CREATE TABLE SZEK (
    ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    SZEKSZAM INT NOT NULL,
    FOGLALT BOOLEAN DEFAULT FALSE
);

CREATE TABLE VETITES (
    ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    FILM_ID INT CONSTRAINT FK_VETITES_FILM_TEREM_SZEK REFERENCES FILM ON DELETE CASCADE ON UPDATE RESTRICT,
    TEREM_ID INT CONSTRAINT FK_VETITES_TEREM_SZEK_FILM REFERENCES TEREM ON DELETE CASCADE ON UPDATE RESTRICT,
    SZEK_ID INT CONSTRAINT FK_VETITES_SZEK_FILM_TEREM REFERENCES SZEK ON DELETE CASCADE ON UPDATE RESTRICT,
    MIKOR VARCHAR(10) NOT NULL,
    IDO VARCHAR(5) NOT NULL
);

CREATE TABLE FOGLALAS (
    ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    SZEK_ID INT CONSTRAINT FK_FOGLALAS_SZEK_FELHASZNALO REFERENCES SZEK ON DELETE CASCADE ON UPDATE RESTRICT,
    FELHASZNALO_ID INT CONSTRAINT FK_FOGLALAS_FELHASZNALO_SZEK REFERENCES FELHASZNALO ON DELETE CASCADE ON UPDATE RESTRICT
);

ALTER TABLE ZOLI.TEREM 
ADD CONSTRAINT NEW_UNIQUE UNIQUE (NEV);

ALTER TABLE ZOLI.FELHASZNALO 
ADD CONSTRAINT NEW_UNIQUE_FELH UNIQUE (NEV);

ALTER TABLE ZOLI.MOZI 
ADD CONSTRAINT NEW_UNIQUE_MOZI UNIQUE (NEV);

ALTER TABLE ZOLI.FILM 
ADD CONSTRAINT NEW_UNIQUE_FILM UNIQUE (CIM);

ALTER TABLE ZOLI.TARTALMAZ 
ADD CONSTRAINT NEW_UNIQUE_TARTALMAZ UNIQUE (TEREM_ID, MOZI_ID);

ALTER TABLE ZOLI.TARTALMAZ 
ADD CONSTRAINT NEW_UNIQUE_VETITES UNIQUE (TEREM_ID, MIKOR);