INSERT INTO ZOLI.MOZI (NEV) 
	VALUES ('Magyar');
INSERT INTO ZOLI.MOZI (NEV) 
	VALUES ('Angol');
INSERT INTO ZOLI.MOZI (NEV) 
	VALUES ('Spanyol');
INSERT INTO ZOLI.MOZI (NEV) 
	VALUES ('Olasz');
INSERT INTO ZOLI.MOZI (NEV) 
	VALUES ('Német')
