INSERT INTO ZOLI.TEREM (NEV, FEROHELY) 
	VALUES ('Szeged', 25);
INSERT INTO ZOLI.TEREM (NEV, FEROHELY) 
	VALUES ('Budapest', 80);
INSERT INTO ZOLI.TEREM (NEV, FEROHELY) 
	VALUES ('Győr', 50);

INSERT INTO ZOLI.TEREM (NEV, FEROHELY) 
	VALUES ('London', 80);

INSERT INTO ZOLI.TEREM (NEV, FEROHELY) 
	VALUES ('Roma', 50);
INSERT INTO ZOLI.TEREM (NEV, FEROHELY) 
	VALUES ('Torino', 50);

INSERT INTO ZOLI.TEREM (NEV, FEROHELY) 
	VALUES ('Madrid', 25);
INSERT INTO ZOLI.TEREM (NEV, FEROHELY) 
	VALUES ('Barcelona', 25);

INSERT INTO ZOLI.TEREM (NEV, FEROHELY) 
	VALUES ('Berlin', 80);